{
    "name": "Employee Requests",
    "version": "16.0.0.1",
    "author": "JERAISY ELECTRONIC SERVICES",
    "license": "AGPL-3",
    "category": "Hr",
    "description": """
    * on this addon you can do:
    - Advance Salary Request
    - Leave Allowance Request
    - OverTime Request
    - Housing Allowance Request
    """,
    "depends": [
        "base",
        "hr",
        "hr_payroll",
        "jes_hr_custody",
        "hr_contract",
        "ent_hr_employee_updation",
        # 'l10n_sa_hr_payroll',
        "jeraisy_hrms",
        "base_address_extended",
        # 'jes_organization_structure',
        "jes_hr_leave",
        "jes_hr_contract",
        "hr_access_base",
        "approvals_management",
    ],
    "data": [
        "data/sequence.xml",
        "data/activity.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/employee.xml",
        "views/leave_request.xml",
        "views/overtime_policy.xml",
        "views/overtime_request.xml",
        "views/letter_request.xml",
        "views/res_config_settings.xml",
        "views/insurance.xml",
        "views/hr_payroll_view.xml",
        "views/resignation_request.xml",
        "views/card_request.xml",
        "views/finance_request.xml",
        "views/breakdwone_request.xml",
        "views/medical_request.xml",
        "views/study_request.xml",
        "views/teckit_request.xml",
        "views/need_request.xml",
        "views/deputation.xml",
        "views/event_request_view.xml",
        "views/event_line_request_view.xml",
        "views/study_include_request.xml",
        "views/overtime_emp_request.xml",
        "views/res_country_view.xml",
        "views/hr_questioning_view.xml",
        "views/menus.xml",
        "views/company.xml",
        "views/loan_request_view.xml",
        "reports/hr_contract_report_view.xml",
        "reports/report_letter.xml",
        "reports/report_salary.xml",
        "reports/report_medical.xml",
        "reports/report_card.xml",
        # 'reports/contract.xml',
        # 'reports/contract_non_saudi.xml',
        # 'reports/contract_non_saudi_worker.xml',
    ],
    "installable": True,
    "application": True,
}
